"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import tinkoff.invest.grpc.common_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OpenSandboxAccountRequest(google.protobuf.message.Message):
    """Запрос открытия счета в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Название счета"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_name", b"_name", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_name", b"_name", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...

global___OpenSandboxAccountRequest = OpenSandboxAccountRequest

@typing.final
class OpenSandboxAccountResponse(google.protobuf.message.Message):
    """Номер открытого счета в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счета"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___OpenSandboxAccountResponse = OpenSandboxAccountResponse

@typing.final
class CloseSandboxAccountRequest(google.protobuf.message.Message):
    """Запрос закрытия счета в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счета"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

global___CloseSandboxAccountRequest = CloseSandboxAccountRequest

@typing.final
class CloseSandboxAccountResponse(google.protobuf.message.Message):
    """Результат закрытия счета в песочнице.
    пустой ответ
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseSandboxAccountResponse = CloseSandboxAccountResponse

@typing.final
class SandboxPayInRequest(google.protobuf.message.Message):
    """Запрос пополнения счета в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счета"""
    @property
    def amount(self) -> tinkoff.invest.grpc.common_pb2.MoneyValue:
        """Сумма пополнения счета в рублях"""

    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        amount: tinkoff.invest.grpc.common_pb2.MoneyValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["amount", b"amount"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "amount", b"amount"]) -> None: ...

global___SandboxPayInRequest = SandboxPayInRequest

@typing.final
class SandboxPayInResponse(google.protobuf.message.Message):
    """Результат пополнения счета, текущий баланс."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCE_FIELD_NUMBER: builtins.int
    @property
    def balance(self) -> tinkoff.invest.grpc.common_pb2.MoneyValue:
        """Текущий баланс счета"""

    def __init__(
        self,
        *,
        balance: tinkoff.invest.grpc.common_pb2.MoneyValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["balance", b"balance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["balance", b"balance"]) -> None: ...

global___SandboxPayInResponse = SandboxPayInResponse
