"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import tinkoff.invest.grpc.common_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class OpenSandboxAccountRequest(google.protobuf.message.Message):
    """Запрос открытия счёта в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Название счёта"""
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_name", b"_name", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_name", b"_name"]) -> typing_extensions.Literal["name"] | None: ...

global___OpenSandboxAccountRequest = OpenSandboxAccountRequest

@typing_extensions.final
class OpenSandboxAccountResponse(google.protobuf.message.Message):
    """Номер открытого счёта в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счёта"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id"]) -> None: ...

global___OpenSandboxAccountResponse = OpenSandboxAccountResponse

@typing_extensions.final
class CloseSandboxAccountRequest(google.protobuf.message.Message):
    """Запрос закрытия счёта в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счёта"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id"]) -> None: ...

global___CloseSandboxAccountRequest = CloseSandboxAccountRequest

@typing_extensions.final
class CloseSandboxAccountResponse(google.protobuf.message.Message):
    """Результат закрытия счёта в песочнице.
    пустой ответ
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CloseSandboxAccountResponse = CloseSandboxAccountResponse

@typing_extensions.final
class SandboxPayInRequest(google.protobuf.message.Message):
    """Запрос пополнения счёта в песочнице."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Номер счёта"""
    @property
    def amount(self) -> tinkoff.invest.grpc.common_pb2.MoneyValue:
        """Сумма пополнения счёта в рублях"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        amount: tinkoff.invest.grpc.common_pb2.MoneyValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["amount", b"amount"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "amount", b"amount"]) -> None: ...

global___SandboxPayInRequest = SandboxPayInRequest

@typing_extensions.final
class SandboxPayInResponse(google.protobuf.message.Message):
    """Результат пополнения счёта, текущий баланс."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BALANCE_FIELD_NUMBER: builtins.int
    @property
    def balance(self) -> tinkoff.invest.grpc.common_pb2.MoneyValue:
        """Текущий баланс счёта"""
    def __init__(
        self,
        *,
        balance: tinkoff.invest.grpc.common_pb2.MoneyValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["balance", b"balance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["balance", b"balance"]) -> None: ...

global___SandboxPayInResponse = SandboxPayInResponse
