site_name: Tinkoff Invest Python SDK
site_url: https://RussianInvestments.github.io/invest-python/
site_description: 'Python SDK, gRPC client, bot examples'

repo_name: 'RussianInvestments/invest-python'
repo_url: 'https://github.com/RussianInvestments/invest-python'
edit_uri: "edit/main/docs/"

copyright: 'Copyright &copy; 2023 Tinkoff'

use_directory_urls: true
nav:
  - 'Главная': 'README.md'
  - 'API Reference':
    - Clients: api/clients.md
  - 'Примеры': 'examples.md'
  - 'Готовые работы': 'robots.md'
  - 'Список изменений': 'CHANGELOG.md'
  - 'Участие в проекте': 'CONTRIBUTING.md'

theme:
  name: material
  language: ru
  palette:
    primary: black
    accent: yellow

plugins:
- include-markdown
- termynal: {}
- search:
    lang: ru
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false

extra_css:
  - custom.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
